### ISSUE TITLE
[Bug Report] 无法正常解码文件。

### ISSUE THREAD

**Issue by execute233** [lc6464/Base16384Coder-Console#2]
无法正常解码文件。
![QQ截图20230824185949](https://github.com/lc6464/Base16384.Net/assets/69996209/85abbe39-536c-4d5e-8243-ab16db6a2b6d)

**Comment by execute233** [comment]
看上去是您的实现类库中Stream.cs第155行有问题。

**Comment by lc6464** [comment]
实现仓库已经发版，等待 NuGet.Org 审核中。

**Comment by lc6464** [comment]
已审核通过，在 `git pull` 后，使用 `dotnet restore --no-cache` 即可。
