### ISSUE TITLE
ConvertFromUtf16BEBytesToUtf8BOMBytes问题

### ISSUE THREAD

**Issue by execute233** [lc6464/Base16384Coder-Console#5]
省空间了，但又没省。
![8IN}O U U4MO`P`PNAVPGHO](https://github.com/lc6464/Base16384.Net/assets/69996209/e1c40187-675c-457b-a0ea-f8a93fade2c8)
![L6V}~`{H(D_L`~{ E(N)34R](https://github.com/lc6464/Base16384.Net/assets/69996209/f978a5df-d108-44fe-b08d-dc011078bfcb)
![5ZU(P_2V${S{F~YEYLHZCIN](https://github.com/lc6464/Base16384.Net/assets/69996209/0e795cca-84ce-4ecb-947a-34097108f2be)

**Comment by execute233** [comment]
@lc6464

**Comment by lc6464** [comment]
你这结果看起来太诡异了。

**Comment by execute233** [comment]
也有可能是你写的诡异？

**Comment by lc6464** [comment]
你帮我看看。

**Comment by execute233** [comment]
你不是要训完了吗？

**Comment by execute233** [comment]
这个Issues应该在Base16384那的。

**Comment by lc6464** [comment]
> 这个Issues应该在Base16384那的。

说得好。

**Comment by execute233** [comment]
看PR，这个关了先。
